### PR TITLE
Js apply multifields

### LINKED ISSUE #323: Replace vector fields
- [x]  Decide form of input, major changes possible. 
	A multifield is just an array of fields. Its description should specify 
	how the number of subfields is determined from the other input data.
	This array allows "transpose" auto conversion (proposed as general mechanism). 

- [x] Change the way Fields are read in, A FieldSet  have method read_input, which pass through the list of Filed descriptors and for every fields it calls virtual method add_change(time, RegionSet, Accessor) and let the Field (or MultiField) store the list of changes. This requires an abstract input accessor.  Duplicate of  #275.

- [x] Implement transposition as general auto conversion method extending current autoconversion of arrays.

in make_storage(Array) if there is non-array on input:
1. set ReaderToStorage::try_transpose_read=1, transpose_index=0, call read of value with array subtype
2. for ReaderToStorage::try_transpose_read=1, check in other make_storage methods that there is Array on input, if so ..
3. ... check that array is non-empty ... else InputException empty array at address ...
4. ... read element at index given by transpose_index using same Input::Type, ASSERT that we ar in array
5. ... for transpose_index==0 add size of array into ReaderToStorage::transpose_array_sizes which is of type vector<unsigned int>
6. ... back in make_storage(Array) check sizes in transpose_array_sizes, and make other calls of reading the subtree for other values of transpose_index.
	
- [x] Use MultiField instead of (variable length) vector valued Fields in all equations. 
	Implement value and value_list in MultiField (can be used in ReactionTerm).
- [x]  Test output of all bulk input fields.

This issue finish effort partly done in #225 and in #172 .
Depends on new input.

### PR DESCRIPTION
**Pull request by jstebel**
Change vector-valued fields into multifields. Required some additional tuning of field classes.
Resolves #323.

### CODE REVIEW

File: src/fields/multi_field.hh [hunk 1]
```diff
@@ -110,7 +110,10 @@ public:
      * We have to override the @p set_mesh method in order to call set_mesh method for subfields.
      */
     void set_mesh(const Mesh &mesh) override;
-
+    
+    
+    MultiField &set_bc(bool is_bc)
```
Comment (jbrezmorf) [inline src/fields/multi_field.hh]: Make this same as for the Field, thus introduce the class BCMultiField.
